import { logger } from '../../config/logger.js';

export interface LLMResponse {
  text: string;
  metadata?: Record<string, unknown>;
}

export interface LLMProvider {
  name: string;
  supportsTools(): boolean;
  supportsVision(): boolean;
  supportsReasoning(): boolean;
  generate(
    systemPrompt: string,
    userPrompt: string,
    history?: Array<{ role: 'user' | 'assistant'; content: string }>
  ): Promise<LLMResponse>;
}

export class MockLLMProvider implements LLMProvider {
  readonly name = 'mock-llm';

  supportsTools(): boolean {
    return false;
  }

  supportsVision(): boolean {
    return false;
  }

  supportsReasoning(): boolean {
    return false;
  }

  async generate(
    systemPrompt: string,
    userPrompt: string,
    _history?: Array<{ role: 'user' | 'assistant'; content: string }>
  ): Promise<LLMResponse> {
    // Return deterministic mock response for demos and testing without api keys
    return {
      text: `[Mock LLM Response]\nBased on your message: "${userPrompt}"\nI am analyzing this context as a Maintainer Agent. All tests are passing successfully!`,
      metadata: {
        mocked: true,
        tokensUsed: 42,
      },
    };
  }
}

export class LiveLLMProvider implements LLMProvider {
  readonly name = 'live-llm';

  constructor(
    private readonly apiKey: string,
    private readonly providerName: string = 'gemini'
  ) {}

  supportsTools(): boolean {
    return true;
  }

  supportsVision(): boolean {
    return true;
  }

  supportsReasoning(): boolean {
    return true;
  }

  async generate(
    systemPrompt: string,
    userPrompt: string,
    history?: Array<{ role: 'user' | 'assistant'; content: string }>
  ): Promise<LLMResponse> {
    // If live API calls are configured, we invoke them. Fallback to mock if API is demo-configured.
    if (!this.apiKey || this.apiKey === 'mock_api_key' || this.apiKey.startsWith('mock')) {
      return new MockLLMProvider().generate(systemPrompt, userPrompt, history);
    }
    // Call the actual Gemini API using native fetch
    try {
      const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${this.apiKey}`;
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [
            {
              role: 'user',
              parts: [
                {
                  text: `System Prompt:\n${systemPrompt}\n\nUser Prompt:\n${userPrompt}`,
                },
              ],
            },
          ],
        }),
      });

      if (!response.ok) {
        const errText = await response.text();
        throw new Error(`Gemini API returned status ${response.status}: ${errText}`);
      }

      const data = (await response.json()) as any;
      const text =
        data.candidates?.[0]?.content?.parts?.[0]?.text || 'No response generated by Gemini.';

      return {
        text,
        metadata: { live: true, model: 'gemini-2.5-flash' },
      };
    } catch (error: any) {
      logger.error({ err: error }, 'Gemini API call failed');
      return {
        text: `[Live Gemini Error] Failed to generate response: ${error.message}`,
        metadata: { live: true, error: true },
      };
    }
  }
}
