import { describe, expect, it } from 'vitest';
import { GitHubResponseAdapter } from '../../src/core/workflow/output-adapters.js';
import { extractGitHubReplyTarget, postGitHubReply } from '../../src/gateway/github/egress.js';
import { fakeGitHubClient } from '../helpers/fixtures.js';

describe('GitHubResponseAdapter', () => {
  it('formats the agent response as a GitHub-flavored markdown comment', () => {
    const adapter = new GitHubResponseAdapter();
    const formatted = adapter.format({
      text: 'Thanks for the report, I have triaged this as a bug.',
      confidence: 0.9,
      actions: [],
      artifacts: [],
      metadata: {},
    });

    expect(formatted).toContain('Thanks for the report, I have triaged this as a bug.');
    expect(formatted).toContain('Reply generated by OSS-Maintainer-AI');
  });
});

describe('GitHub egress target extraction', () => {
  it('extracts owner/repo/issueNumber from UnifiedEvent metadata', () => {
    const target = extractGitHubReplyTarget({
      github: { owner: 'darkraider01', repo: 'OSS-Maintainer-AI', issueNumber: 42 },
    });
    expect(target).toEqual({ owner: 'darkraider01', repo: 'OSS-Maintainer-AI', issueNumber: 42 });
  });

  it('returns null when metadata is missing required fields', () => {
    expect(extractGitHubReplyTarget({})).toBeNull();
    expect(extractGitHubReplyTarget({ github: { owner: 'darkraider01' } })).toBeNull();
  });
});

describe('GitHub API egress (postGitHubReply)', () => {
  it('posts a comment and returns the created comment on success', async () => {
    const client = fakeGitHubClient();
    const target = { owner: 'darkraider01', repo: 'OSS-Maintainer-AI', issueNumber: 42 };

    const comment = await postGitHubReply(client, target, 'Thanks for reporting this!');

    expect(comment.id).toBeDefined();
    expect(comment.htmlUrl).toContain('darkraider01/OSS-Maintainer-AI/issues/42');
    expect(client.comments).toHaveLength(1);
    expect(client.comments[0]).toEqual({
      owner: 'darkraider01',
      repo: 'OSS-Maintainer-AI',
      issueNumber: 42,
      body: 'Thanks for reporting this!',
    });
  });

  it('propagates GitHub API failures instead of swallowing them', async () => {
    const failingClient = fakeGitHubClient();
    failingClient.postIssueComment = async () => {
      throw new Error('GitHub API error: 403 rate limited');
    };
    const target = { owner: 'darkraider01', repo: 'OSS-Maintainer-AI', issueNumber: 42 };

    await expect(postGitHubReply(failingClient, target, 'hello')).rejects.toThrow(
      'GitHub API error: 403 rate limited'
    );
  });
});
