import { beforeAll, describe, expect, it } from 'vitest';
import { CommunicationService } from '../../src/gateway/adapters/communication-service.js';
import { DeduplicationService } from '../../src/gateway/adapters/deduplication-service.js';
import { ConversationService } from '../../src/gateway/adapters/conversation-service.js';
import { IdentityService } from '../../src/gateway/adapters/identity-service.js';
import { MessagePersistenceService } from '../../src/gateway/adapters/message-persistence-service.js';
import { EventBus } from '../../src/gateway/event-bus.js';
import { Runtime as AgentRuntime } from '../../src/core/runtime.js';
import { MaintainerAgent } from '../../src/core/agent/maintainer-agent.js';
import { normalizeGitHubWebhookEvent } from '../../src/gateway/adapters/github.js';
import { runSqliteMigrations } from '../helpers/migrate-sqlite.js';
import { issuesOpenedPayload } from '../helpers/fixtures.js';

function buildWiring() {
  const dedup = new DeduplicationService();
  const conv = new ConversationService();
  const ident = new IdentityService();
  const persist = new MessagePersistenceService();
  const bus = new EventBus();
  const replies: Record<string, string> = {};

  const commService = new CommunicationService(dedup, conv, ident, persist, async (envelope) => {
    envelope.respond = async (text: string) => {
      replies[envelope.payload.provider] = text;
    };
    await bus.publish(envelope as any);
  });

  const agentRuntime = new AgentRuntime({ demoMode: true });
  bus.subscribe(async (envelope) => {
    if (envelope.payload) await agentRuntime.processEvent(envelope);
  });

  return { commService, agentRuntime, replies };
}

describe('GitHub reaches the shared CommunicationService -> MaintainerAgent pipeline', () => {
  beforeAll(() => {
    runSqliteMigrations();
  });

  it('processes a GitHub issue through CommunicationService and MaintainerAgent, formatted by GitHubResponseAdapter', async () => {
    const { commService, replies } = buildWiring();

    const normalized = normalizeGitHubWebhookEvent({
      eventName: 'issues',
      deliveryId: 'e2e-delivery-1',
      payload: issuesOpenedPayload(),
    })!;

    const envelope = await commService.ingest(normalized.rawMessage, 'github');

    expect(envelope).not.toBeNull();
    expect(replies.github).toBeDefined();
    // The fixture body ("Steps to reproduce: 1. ... 2. ...") reads as a bug
    // report, so it's routed to Issue Triage (#18) rather than the generic
    // LLM fallback — it already found reproduction steps and asks for what's
    // still missing.
    expect(replies.github).toContain('Could you provide');
    expect(replies.github).toContain('SDK/library version');
    expect(replies.github).toContain('Reply generated by OSS-Maintainer-AI');
  });

  it('routes GitHub, Slack, and Discord raw messages through the exact same MaintainerAgent instance', async () => {
    const { commService, agentRuntime, replies } = buildWiring();
    const sharedAgent = agentRuntime.agentRegistry.find('maintainer-agent');
    expect(sharedAgent).toBeInstanceOf(MaintainerAgent);

    const executedOn: unknown[] = [];
    const originalExecute = sharedAgent!.execute.bind(sharedAgent);
    sharedAgent!.execute = async (context) => {
      executedOn.push(sharedAgent);
      return originalExecute(context);
    };

    const githubNormalized = normalizeGitHubWebhookEvent({
      eventName: 'issues',
      deliveryId: 'shared-delivery-github',
      payload: issuesOpenedPayload(),
    })!;

    await commService.ingest(githubNormalized.rawMessage, 'github');
    await commService.ingest(
      {
        id: 'shared-delivery-slack',
        conversationId: 'C_SLACK_SHARED',
        channel: 'slack',
        sender: { id: 'U_SHARED', username: 'shared_user' },
        text: 'hello from slack',
      },
      'slack'
    );
    await commService.ingest(
      {
        id: 'shared-delivery-discord',
        conversationId: 'D_DISCORD_SHARED',
        channel: 'discord',
        sender: { id: 'D_SHARED', username: 'shared_discord_user' },
        text: 'hello from discord',
      },
      'discord'
    );

    // Same agent instance handled all three providers — one AI maintainer, three adapters.
    expect(executedOn).toHaveLength(3);
    expect(new Set(executedOn).size).toBe(1);
    expect(executedOn[0]).toBe(sharedAgent);

    expect(replies.github).toContain('Reply generated by OSS-Maintainer-AI');
    expect(replies.slack).toContain('🤖 *OSS-Maintainer-AI*:');
    expect(replies.discord).toContain('[Mock LLM Response]');
  });
});
