import { beforeAll, describe, expect, it, vi } from 'vitest';
import { bootstrap } from '../../src/index.js';
import { runSqliteMigrations } from '../helpers/migrate-sqlite.js';
import { fakeClient } from '../helpers/fixtures.js';

describe('End-to-End Agent Workflow Integration', () => {
  beforeAll(() => {
    runSqliteMigrations();
  });

  it('runs E2E flow from GitHub Issue raw payload to GitHub comment reply using MockLLM', async () => {
    const client = fakeClient();
    const runtime = await bootstrap({ client });

    // Verify bootstrap wires components
    expect(runtime.gateway).toBeDefined();
    expect(runtime.agentRuntime).toBeDefined();

    const rawGithubMessage = {
      id: 'issue_msg_999',
      conversationId: 'gh_issue_456',
      channel: 'github',
      sender: {
        id: '4242',
        login: 'octocat',
        display_name: 'The Octocat',
      },
      text: 'Please review this code',
      subject: 'Review request',
      raw: {
        id: 'issue_msg_999',
        conversation_id: 'gh_issue_456',
        channel: 'github',
        sender: {
          id: '4242',
          login: 'octocat',
        },
        text: 'Please review this code',
      },
    };

    await runtime.gateway.ingest(rawGithubMessage as any);

    // Assert that MockLLM resolved and triggered ResponseAdapter correctly
    expect(client.replies).toHaveLength(1);
    expect(client.replies[0].messageId).toBe('issue_msg_999');
    expect(client.replies[0].text).toContain('[Mock LLM Response]');
    expect(client.replies[0].text).toContain('Please review this code');
    expect(client.replies[0].text).toContain('*Reply generated by OSS-Maintainer-AI*'); // GitHubResponseAdapter formatting

    await runtime.shutdown();
  });

  it('runs E2E flow from Slack Mention raw payload to Slack thread response using MockLLM', async () => {
    const client = fakeClient();
    const runtime = await bootstrap({ client });
    (runtime.gateway as any).enabledChannels.add('slack');

    // 2. Simulate Slack Ingress Message
    const rawSlackMessage = {
      id: 'slack_ts_12345',
      conversationId: 'C_SLACK_789',
      channel: 'slack',
      sender: {
        id: 'U_SLACK_USER',
        username: 'slackuser',
        display_name: 'Slack User',
      },
      text: 'hello @maintainer-agent',
      subject: null,
      raw: {
        id: 'slack_ts_12345',
        conversation_id: 'C_SLACK_789',
        channel: 'slack',
        sender: {
          id: 'U_SLACK_USER',
          username: 'slackuser',
        },
        text: 'hello @maintainer-agent',
        ts: '17890000.000100',
        thread_ts: '17890000.000000',
      },
    };

    await runtime.gateway.ingest(rawSlackMessage as any);

    expect(client.replies).toHaveLength(1);
    expect(client.replies[0].messageId).toBe('slack_ts_12345');
    expect(client.replies[0].text).toContain('[Mock LLM Response]');
    expect(client.replies[0].text).toContain('hello @maintainer-agent');
    expect(client.replies[0].text).toContain('🤖 *OSS-Maintainer-AI*:'); // SlackResponseAdapter formatting

    await runtime.shutdown();
  });
});
