import type { AgentResponse } from '../agent/agent-types.js';
import type { ProviderKey } from '../../gateway/unified-event.js';

export interface ResponseAdapter {
  format(response: AgentResponse): string;
}

export class GitHubResponseAdapter implements ResponseAdapter {
  format(response: AgentResponse): string {
    // Return markdown comment signature for GitHub
    return `${response.text}\n\n*Reply generated by OSS-Maintainer-AI*`;
  }
}

export class SlackResponseAdapter implements ResponseAdapter {
  format(response: AgentResponse): string {
    // Return formatting suitable for Slack block layout
    return `🤖 *OSS-Maintainer-AI*:\n${response.text}`;
  }
}

export class OutputAdapters {
  private readonly adapters = new Map<ProviderKey, ResponseAdapter>();

  constructor() {
    this.adapters.set('github', new GitHubResponseAdapter());
    this.adapters.set('slack', new SlackResponseAdapter());
  }

  format(provider: ProviderKey, response: AgentResponse): string {
    const adapter = this.adapters.get(provider);
    if (!adapter) {
      return response.text;
    }
    return adapter.format(response);
  }
}
